### PR TITLE
Dev gpu fix

### PR DESCRIPTION
**Pull request by fjansson**
Fixes after merging the Ruisdael and RRTMGP branches.

### CODE REVIEW

**Comment by lsoucasse** [comment]
Hi @fjansson, just checkout your branch, waiting for snellius to test it...

**Review by CasparJungbacker — APPROVED** [review]

**Comment by lsoucasse** [comment]
Hi @fjansson, Currently the botany case crashes with this commit because of tracers being not read properly (though I modified the nameoption file and scalar.inp file with Caspar). Weirdly this reading problem only appear on the GPU and not on the CPU. I will try to add your moment calculation change into my old radiation branch to see if it fixes the issue of having Nan values in stat fields.

**Comment by fjansson** [comment]
@lsoucasse I got Botany working with this branch:
add this to namoptions. Capitaliztion of the scalar names is important:
```
&NAMTRACERS                                                                                                                 
ltracers = .true.                                                                                                           
tracernames = 'nr', 'qr'                                                                                                    
/ 
```
edit scalar.inp.001, change the second line to
```                                                                      
#height               nr          qr        
```
here there should be three words separated by white space, and capitalization might matter again. (There's a tolower call somewhere in the initialization but not everywhere).

**Comment by lsoucasse** [comment]
> @lsoucasse I got Botany working with this branch: add this to namoptions. Capitaliztion of the scalar names is important:
> 
> ```
> &NAMTRACERS                                                                                                                 
> ltracers = .true.                                                                                                           
> tracernames = 'nr', 'qr'                                                                                                    
> / 
> ```
> 
> edit scalar.inp.001, change the second line to
> 
> ```
> #height               nr          qr        
> ```
> 
> here there should be three words separated by white space, and capitalization might matter again. (There's a tolower call somewhere in the initialization but not everywhere).

Hi @fjansson, I can read the tracers in the botany case, but still have the issue with my other column test cases while following the same procedure, formatting issue I suppose.

So I ran a couple of iterations of the botany case on the gpu interactive node that worked fine! But then running on a regular node gives me again a netcdf error when writing statistics, I am curious to know if you experience it or not.

**Review by lsoucasse — APPROVED** [review]

**Pull request merged**
