### PR TITLE
Enable FFTW by default

### PR DESCRIPTION
**Pull request by CasparJungbacker**
Since most systems have FFTW installed anyway:
- Set USE_FFTW to ON
- Set solver_id to 100 when USE_FFTW is defined

FFTW can still be disabled by setting `-DUSE_FFTW=False`.

### CODE REVIEW

**Comment by CasparJungbacker** [comment]
@fjansson looking at the compilation CI pipeline, should we also remove all tests with `-DUSE_FFTW=True`?

**Comment by fjansson** [comment]
we could remove them but instead add at least some test with `-DUSE_FFTW=False`

**Comment by fjansson** [comment]
To keep the number of compilation tests down, I'd say we don't need to test all combinations with -DUSE_FFTW=False. Testing one could be nice... but more important is that DALES still runs with the old FFT.

**Comment by CasparJungbacker** [comment]
Ah, saw your comment right after I enabled tests for `-DUSE_FFTW=F` 😂 I'll revert that one, and add a test run of BOMEX with FFTW disabled then.

**Comment by CasparJungbacker** [comment]
Upon closer inspection, I saw this in the testing configuration:

```python
@pytest.mark.parametrize("solver", [0, 100]) # FFTPACK & FFTW
```

meaning that we've been testing for both the included FFT lib and FFTW for some time now 👍

**Review by fjansson — APPROVED** [review]

**Pull request merged**
